component:
  rest:
  connectionRequestTimeout: 2000
  connectTimeout: 2000
  readTimeout: 10000

git:
  gitlabUrl: XXX
  apiVersion: /api/v4
  privateToken: XX  # gitlab accessToken  http://my.office.hupun.com:5180/profile/personal_access_tokens
  projectDir: XX # 存放路径
  group: XXXX # 跨境项目
  ignores:
    - kuaixun
    - app
    - archive
    - calf
    - cerp-drp
    - production
    - test
    - tools
    - whse-pda-api
    - whse-pda-api-starter
    - calf-whse-suit-starter
    - calf-whse-web-starter
    - erp-base-starter
    - cerp-whse-starter
    - whse-pda
    - whse-view